# Generated by Django 5.2.8 on 2025-12-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cli', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('domicilio', models.CharField(max_length=300, verbose_name='Domicilio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('cod_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('cod_lectura', models.AutoField(primary_key=True, serialize=False)),
                ('ano_consumo', models.IntegerField(verbose_name='Año de Consumo')),
                ('mes_consumo', models.IntegerField(verbose_name='Mes de Consumo')),
                ('suministro_numero', models.CharField(max_length=50, verbose_name='Nº Suministro')),
                ('area', models.CharField(max_length=50, verbose_name='Área')),
                ('ruta', models.CharField(max_length=50, verbose_name='Ruta')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('tipo_medidor', models.CharField(max_length=50, verbose_name='Tipo de Medidor')),
                ('numero_medidor', models.CharField(max_length=50, verbose_name='Nº Medidor')),
                ('lectura_anterior', models.IntegerField(verbose_name='Lectura Anterior')),
                ('lectura_actual', models.IntegerField(blank=True, null=True, verbose_name='Lectura Actual')),
                ('consumo_kwh', models.IntegerField(blank=True, null=True, verbose_name='Consumo (kWh)')),
                ('novedad_libre', models.TextField(blank=True, null=True, verbose_name='Novedad Libre')),
                ('enviado_comercial', models.BooleanField(default=False, verbose_name='Enviado a Comercial')),
                ('abierta', models.BooleanField(default=True, verbose_name='Ruta Abierta')),
                ('fecha_hora_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Registro')),
                ('ubi_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación GPS')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='lecturas.cliente')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'ordering': ['ano_consumo', 'mes_consumo', 'ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='NovedadLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.lote')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.novedad')),
            ],
            options={
                'verbose_name': 'Novedad de Lectura',
                'verbose_name_plural': 'Novedades de Lecturas',
                'unique_together': {('lectura', 'novedad')},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='novedades',
            field=models.ManyToManyField(blank=True, through='lecturas.NovedadLectura', to='lecturas.novedad'),
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('cod_ope', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='lecturas.operador'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['ano_consumo', 'mes_consumo'], name='lecturas_lo_ano_con_adaca1_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['ruta'], name='lecturas_lo_ruta_04d5d3_idx'),
        ),
    ]
